# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41068c57868cfe1a95420df4bfca0d6bec7d8005eaf21adede57be5065488793b3f67a24ff6515954b9170e58fecb7c948de692186edf8d7e258d49b757c27b2

test:
  secret_key_base: 3ed61559a5dbc329923cda989294869d50f4b1384442eb6e3018a1622b71b40d70f92765501ce3ffafa00937d2a276b9fe38625dc2fedf685fd589723103b9b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
